---
version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15

jobs:

  # sanity
  go-checks:
    docker:
      - image: circleci/golang:1.13-stretch
    steps:
      - checkout
      - run:
          name: Run fmt.Errorf Usage Check
          command: |
            if grep -r --include=*.go fmt.Errorf . ; then
              echo "Please use errors.Errorf (or errors.New or errors.Wrap or errors.Wrapf) as appropriate rather than fmt.Errorf"
              exit 1
            fi
      - run:
          name: Build
          command: go build ./...
      - run: ./.circleci/check_dependencies.sh
      - run:
          name: Unit Tests
          command: |
            mkdir -p ~/junit/
            gotestsum --junitfile ~/junit/unit-tests.xml -- -short $(go list ./...)
      - run:
          name: lint
          command: |
            ./.circleci/lint-download.sh
            GOGC=50 golangci-lint run
      - run:
          name: license lint
          command: |
            go get github.com/denis-tingajkin/go-header@v0.2.0
            go-header
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
    environment:
      GO111MODULE: "on"
  yaml-checks:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: yamllint
          command: |
            pip install --user yamllint
            /home/circleci/.local/bin/yamllint -c .yamllint.yml --strict .

# workflows
workflows:
  version: 2
  checks:
    jobs:
      - go-checks
      - yaml-checks
      - shellcheck/check
