---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot'}}
    uses: networkservicemesh/.github/.github/workflows/automerge.yaml@main
