---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'release/') }}
    uses: networkservicemesh/.github/.github/workflows/release.yaml@main
    with:
      dependent_repositories: |
        ["sdk-k8s",
        "sdk-kernel",
        "cmd-nsmgr",
        "cmd-nsmgr-proxy",
        "cmd-registry-memory",
        "cmd-registry-proxy-dns",
        "cmd-nse-remote-vlan",
        "cmd-nse-vfio",
        "cmd-nsc-init",
        "cmd-ipam-vl3",
        "cmd-map-ip-k8s",
        "cmd-admission-webhook-k8s"]

    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
