---
name: Update dependent repositories
on:
  push:
    branches:
      - master

jobs:
  update-dependent-repositories:
    strategy:
      matrix:
        repository: [cmd-registry-memory, cmd-registry-proxy-dns, sdk-kernel, sdk-vppagent, cmd-nsmgr]
    name: Update ${{ matrix.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - name: Find merged PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ github.token }}
      - name: Create commit message
        working-directory: ${{ github.repository }}
        run: |
          echo "Update go.mod and go.sum to latest version from ${{ github.repository }}@master ${{ github.repository }}#${{ steps.findPr.outputs.pr }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          echo "${{ github.repository }} PR link: https://github.com/${{ github.repository }}/pull/${{ steps.findPr.outputs.pr }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          echo "${{ github.repository }} commit message:" >> /tmp/commit-message
          git log -1 >> /tmp/commit-message
          echo "Commit Message:"
          cat /tmp/commit-message

      - uses: actions/checkout@v2
        with:
          path: networkservicemesh/${{ matrix.repository }}
          repository: networkservicemesh/${{ matrix.repository }}
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Update ${{ github.repository }} locally
        working-directory: networkservicemesh/${{ matrix.repository }}
        run: |
          GOPROXY=direct go get -u github.com/${{ github.repository }}
          go mod tidy
          git diff
      - name: Push update to the ${{ matrix.repository }}
        working-directory: networkservicemesh/${{ matrix.repository }}
        run: |
          echo Starting to update repositotry ${repository}
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add go.mod go.sum
          git commit -s -m "Update go.mod and go.sum to latest version from networkservicemesh/sdk@master"
          git checkout -b update/sdk-gomod
          git push -f origin update/sdk-gomod
